[package]
name = "custom_token"
version = "1.0.0"
upgrade_policy = "compatible"

[addresses]
custom_token_addr = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "main", subdir = "aptos-move/framework/aptos-framework"}
AptosTokenObjects = {git = "https://github.com/aptos-labs/aptos-core.git", rev = "main", subdir = "aptos-move/framework/aptos-token-objects"}

# For use when developing and testing this module
[dev-addresses]
custom_token_addr = "0x100"